_target_: src.datamodules.narrative_datamodule.NarrativeDataModule

batch_size: ${batch_size}
num_workers: ${num_workers}
len_ques: 42
len_para: 500
len_para_processing: 120
len_ans: 15

path_bert: ${PATH.bert}
path_data: ${PATH.data}
path_raw_data: ${PATH.raw_data}
path_processed_contx: ${PATH.processed_contx}
